# Cloudflare Pages configuration for frontend deployment
name = "rental-management-frontend"
compatibility_date = "2025-03-07"
pages_build_output_dir = "dist"

[build]
command = "npm run build:production"
cwd = "."
watch_dir = "src"

# Environment variables for production
[env.production.vars]
VITE_API_BASE_URL = "https://rental-management-api.amin-chinisaz-edu.workers.dev"
VITE_APP_ENV = "production"

[env.preview.vars]
VITE_API_BASE_URL = "https://rental-management-api.amin-chinisaz-edu.workers.dev"
VITE_APP_ENV = "development"