name = "rental-management-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Enable observability for monitoring
[observability]
enabled = true

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "rental-management-db"
database_id = "rental-management-db" # Will be replaced with actual ID after D1 creation

# KV Namespace for caching and sessions
[[kv_namespaces]]
binding = "RENTAL_KV"
id = "rental-kv-namespace" # Will be replaced with actual ID after KV creation

# Environment variables (non-sensitive)
[vars]
ENVIRONMENT = "production"

# Secrets (sensitive data - set via wrangler secret put)
# JWT_SECRET - JWT signing secret
# EMAIL_USER - Email service username/API key
# EMAIL_PASS - Email service password/API secret
# TELEGRAM_BOT_TOKEN - Telegram bot token
# WHATSAPP_ACCOUNT_SID - Twilio WhatsApp Account SID
# WHATSAPP_AUTH_TOKEN - Twilio WhatsApp Auth Token

# Build configuration
[build]
command = "npm run build"

# Development configuration
[env.development]
name = "rental-management-api-dev"

[env.development.vars]
ENVIRONMENT = "development"

# Production configuration  
[env.production]
name = "rental-management-api"

[env.production.vars]
ENVIRONMENT = "production"