name = "rental-management-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Enable observability for monitoring
[observability]
enabled = true

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "rental-management-db"
database_id = "YOUR_D1_DATABASE_ID" # Replace with actual database ID after creation

# KV Namespace for caching and sessions
[[kv_namespaces]]
binding = "RENTAL_KV"
id = "YOUR_KV_NAMESPACE_ID" # Replace with actual KV namespace ID

# Environment variables (non-sensitive)
[vars]
ENVIRONMENT = "production"
APP_NAME = "Professional Rental Management System"
APP_VERSION = "2.0.0"
DEFAULT_LOCALE = "fa-IR"

# Secrets (sensitive data - set via wrangler secret put)
# JWT_SECRET - JWT signing secret (generate with generate-session-secret.js)
# EMAIL_USER - Email service username/API key (Resend API key recommended)
# EMAIL_PASS - Email service password/API secret
# TELEGRAM_BOT_TOKEN - Telegram bot token (optional)
# WHATSAPP_ACCOUNT_SID - Twilio WhatsApp Account SID (optional)
# WHATSAPP_AUTH_TOKEN - Twilio WhatsApp Auth Token (optional)

# Build configuration
[build]
command = "npm run build"

# Assets configuration for static files
[assets]
bucket = "./client/dist"
binding = "ASSETS"

# Development configuration
[env.development]
name = "rental-management-api-dev"

[env.development.vars]
ENVIRONMENT = "development"

[[env.development.d1_databases]]
binding = "DB"
database_name = "rental-management-db-dev"
database_id = "YOUR_DEV_D1_DATABASE_ID"

# Production configuration  
[env.production]
name = "rental-management-api"

[env.production.vars]
ENVIRONMENT = "production"

[[env.production.d1_databases]]
binding = "DB"
database_name = "rental-management-db"
database_id = "YOUR_PROD_D1_DATABASE_ID"

# Route configuration for Pages integration
[[routes]]
pattern = "/api/*"
zone_name = "your-domain.com"

# Headers configuration
[headers]
"/*" = [
  { key = "X-Frame-Options", value = "DENY" },
  { key = "X-Content-Type-Options", value = "nosniff" },
  { key = "Referrer-Policy", value = "strict-origin-when-cross-origin" },
  { key = "Permissions-Policy", value = "geolocation=(), microphone=(), camera=()" }
]